In [1]:
import torch
import numpy as np

# 一、索引

In [3]:
tensor = torch.randn(4, 4)

print(tensor)

print(f'第一行：{tensor[0]}')
print(f'第一列：{tensor[:, 0]}')
print(f'最后一列：{tensor[..., -1]}')
print(f'最后一列2：{tensor[:, -1]}')

tensor[:,1] = 0
print(tensor)

tensor([[-0.1011,  0.6165,  0.6514, -2.2404],
        [ 0.7451,  1.4354,  0.3104,  0.9309],
        [ 0.5847, -2.0065,  0.4187, -0.1437],
        [-1.2811,  0.2336, -1.2405, -0.6751]])
第一行：tensor([-0.1011,  0.6165,  0.6514, -2.2404])
第一列：tensor([-0.1011,  0.7451,  0.5847, -1.2811])
最后一列：tensor([-2.2404,  0.9309, -0.1437, -0.6751])
最后一列2：tensor([-2.2404,  0.9309, -0.1437, -0.6751])
tensor([[-0.1011,  0.0000,  0.6514, -2.2404],
        [ 0.7451,  0.0000,  0.3104,  0.9309],
        [ 0.5847,  0.0000,  0.4187, -0.1437],
        [-1.2811,  0.0000, -1.2405, -0.6751]])


# 二、运算
## 1、加减乘除

In [ ]:
tensor1 = torch.tensor([
  [1, 2], [3, 4]
])
tensor2 = torch.tensor([
  [5, 6], [7, 8]
])

# 加法
print(tensor1 + tensor2)
# 讲所有元素求和
sum = tensor1.sum()
print(sum)
print(sum.item())

# 减法
print('减法')
print(tensor1 - tensor2)

# 乘法
print('乘法')
# 矩阵乘法
print(tensor1 @ tensor2)
# element-wise 乘法：类似矩阵加法，将每个对应元素相乘
print(tensor1 * tensor2)

# 除法
print('除法')
print(tensor1 / tensor2)

# 幂运算
print('幂运算')
print(tensor1 ** tensor2)




tensor([[ 6,  8],
        [10, 12]])
tensor(10)
10
tensor([[-4, -4],
        [-4, -4]])
乘法
tensor([[19, 22],
        [43, 50]])
tensor([[ 5, 12],
        [21, 32]])
除法
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
幂运算
tensor([[    1,    64],
        [ 2187, 65536]])


## 2、拼接

torch.cat(tensors, dim=0, out=None)

参数说明：

tensors (必需): 要连接的张量序列，可以是元组或列表

dim (可选): 连接的维度，默认为 0

out (可选): 输出张量

In [ ]:
tensor1 = torch.tensor([
  [1, 2], [3, 4]
])
tensor2 = torch.tensor([
  [5, 6], [7, 8]
])

# dim = 0， 沿行方向连接
print(torch.cat((tensor1, tensor2), dim=0))
# dim = 1， 沿列方向连接
print(torch.cat((tensor1, tensor2), dim=1))




tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
tensor([[1, 3],
        [2, 4]])
