In [2]:
import torch
import numpy as np

In [4]:
print(torch.backends.mps.is_available())  # 如果返回 True，就可以使用 device='mps'

True


# 一、属性

## 1、rand
torch.rand(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
### 1.1 *size（必需）：输出张量的形状，可以是多个整数或元组。例如：
torch.rand(3) → 形状为 [3] 的一维张量 

torch.rand(2, 3) → 形状为 [2, 3] 的二维张量 

torch.rand(2, 3, 4) → 形状为 [2, 3, 4] 的三维张量，生成2个3行4列的数组

In [ ]:
tensor = torch.rand(2, 3)
print(tensor)

print(111, tensor.shape)
print(222, tensor.dtype)
print(333, tensor.device)

tensor2 = torch.rand(2, 3, device='mps')
print(tensor2.device)
# 打印结果为 mps:0 表示 MPS 已可用，张量已创建在 GPU 上。
# mps:0 的含义：
# mps：使用 Mac 的 GPU（Metal Performance Shaders）
# :0：第一个 MPS 设备（类似 CUDA 的 cuda:0）



tensor([[0.6075, 0.8044, 0.6963],
        [0.5118, 0.9430, 0.4403]])
111 torch.Size([2, 3])
222 torch.float32
333 cpu
mps:0


## 2、定义tensor

In [ ]:
# 存储数据
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [ ]:
data = [[1, 2], [3, 4]]
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)


tensor([[1, 2],
        [3, 4]])


In [ ]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

# 保持了x_data的数据属性和形状
# 元素全为 1
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: {x_ones}")

# 随机初始化
# 保持了x_data的形状，重新定义数据属性（类型）
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: {x_rand}")


Ones Tensor: tensor([[1, 1],
        [1, 1]])
Random Tensor: tensor([[0.7760, 0.1950],
        [0.0037, 0.4421]])


# 二、存储设备

In [3]:
# 比较 CPU 和 GPU 的速度
import time

# CPU 测试
start = time.time()
a_cpu = torch.rand(10000, 10000)
b_cpu = torch.rand(10000, 10000)
c_cpu = a_cpu @ b_cpu
cpu_time = time.time() - start

# GPU 测试
start = time.time()
a_mps = torch.rand(10000, 10000, device='mps')
b_mps = torch.rand(10000, 10000, device='mps')
c_mps = a_mps @ b_mps
mps_time = time.time() - start

print(f"CPU 时间: {cpu_time} 秒")
print(f"GPU 时间: {mps_time} 秒")


CPU 时间: 1.3821320533752441 秒
GPU 时间: 0.2409069538116455 秒


In [5]:
data = [[1, 2], [3, 4]]
tensor = torch.tensor(data)

gpu_tensor = tensor.to('mps')

cpu_tensor = tensor.to('cpu')

print(gpu_tensor)
print(cpu_tensor)






tensor([[1, 2],
        [3, 4]], device='mps:0')
tensor([[1, 2],
        [3, 4]])
