In [7]:
import torch
import numpy as np
from PIL import Image
from torchvision import transforms

# numpy & tensor

In [2]:
n = np.ones(5)
t = torch.from_numpy(n)

print(n)
print(t)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [6]:
t = torch.randint(0, 10, (2, 3))
n = t.numpy()
print(t)
print(n)

tensor([[6, 3, 1],
        [3, 6, 2]])
[[6 3 1]
 [3 6 2]]


# tensor VS 图片

In [10]:
image_path = '../数学/img/origin.png'
image = Image.open(image_path)

transform = transforms.ToTensor()
tensor_image = transform(image)

print(type(tensor_image))
print(tensor_image)





<class 'torch.Tensor'>
tensor([[[0.0706, 0.0706, 0.0706,  ..., 0.0745, 0.0745, 0.0824],
         [0.0745, 0.0745, 0.0745,  ..., 0.0745, 0.0745, 0.0745],
         [0.0745, 0.0745, 0.0745,  ..., 0.0706, 0.0706, 0.0745],
         ...,
         [0.1137, 0.1216, 0.1255,  ..., 0.1255, 0.1255, 0.1216],
         [0.1137, 0.1216, 0.1255,  ..., 0.1255, 0.1255, 0.1216],
         [0.1137, 0.1255, 0.1333,  ..., 0.1216, 0.1255, 0.1216]],

        [[0.0706, 0.0706, 0.0706,  ..., 0.0824, 0.0824, 0.0863],
         [0.0706, 0.0706, 0.0706,  ..., 0.0824, 0.0824, 0.0863],
         [0.0706, 0.0706, 0.0706,  ..., 0.0824, 0.0824, 0.0863],
         ...,
         [0.1255, 0.1333, 0.1412,  ..., 0.1412, 0.1412, 0.1412],
         [0.1216, 0.1294, 0.1412,  ..., 0.1373, 0.1412, 0.1412],
         [0.1216, 0.1333, 0.1412,  ..., 0.1333, 0.1373, 0.1412]],

        [[0.0784, 0.0784, 0.0824,  ..., 0.1059, 0.1059, 0.1098],
         [0.0784, 0.0824, 0.0824,  ..., 0.1059, 0.1059, 0.1098],
         [0.0784, 0.0824, 0.0824,  

## torch.randn()

torch.randn()：生成服从标准正态分布（均值 0，标准差 1）的随机数

(3, 224, 224)：张量的形状（维度）

形状含义：

3：通道数（通常表示 RGB 的 3 个通道）

224：高度（像素）

224：宽度（像素）

In [11]:
tensor_image = torch.randn((3, 224, 224))
print(tensor_image)
transformed_image = transforms.ToPILImage()(tensor_image)
save_path = '../数学/img/transformed_image.png'
transformed_image.save(save_path)











tensor([[[-0.3735,  1.0638, -0.1675,  ...,  1.7622,  1.1219, -0.2943],
         [ 2.1047, -0.1834,  0.7083,  ...,  0.8116,  0.3189, -0.2387],
         [-1.1732, -0.3830, -0.1121,  ..., -2.0776, -0.4606, -2.2140],
         ...,
         [ 0.2442, -2.1129, -1.2404,  ...,  1.0347,  0.0998,  0.3205],
         [-0.4889, -0.0448,  1.8411,  ..., -0.9692, -1.2130,  0.5982],
         [ 1.8640, -0.6641, -2.1529,  ...,  1.4755,  0.0207,  1.2990]],

        [[ 0.9101, -0.0187,  0.6255,  ..., -1.3940, -0.5071, -0.2101],
         [ 1.6682,  0.3979,  1.3993,  ...,  0.0303,  0.3233, -0.2370],
         [ 0.3326,  1.3278,  1.5707,  ...,  1.3781,  0.8132,  1.6935],
         ...,
         [ 0.7209,  1.6119, -0.0751,  ...,  0.9575, -1.4143,  1.7222],
         [-1.6083, -0.1404,  0.9137,  ..., -2.4685, -0.1043, -0.1542],
         [-1.3127, -0.4739, -0.7267,  ...,  0.1376,  0.3250, -0.2617]],

        [[-0.4984, -0.5617,  0.1117,  ...,  0.1141,  0.2268, -1.3528],
         [ 0.3731,  0.3836,  0.2709,  ..., -0

# pytorch 处理图片
模拟从硬盘读取一张图片，使用pytorch在显卡上进行运算，然后把运算结果保存到硬盘

In [ ]:
image_path = '../数学/img/origin.png'
image = Image.open(image_path)

# 会自动归一化：将0-255之间的数变成0到1
transform = transforms.ToTensor()
tensor_image = transform(image)
print(tensor_image.device)

gput_tenser_image = tensor_image.to('mps')
print(gput_tenser_image.device)

gput_tenser_image += 0.2
print(gput_tenser_image)

pil_image = transforms.ToPILImage()(gput_tenser_image)
pil_image.save('../数学/img/transformed_image_add.png')







cpu
mps:0
tensor([[[0.2206, 0.2206, 0.2206,  ..., 0.2245, 0.2245, 0.2324],
         [0.2245, 0.2245, 0.2245,  ..., 0.2245, 0.2245, 0.2245],
         [0.2245, 0.2245, 0.2245,  ..., 0.2206, 0.2206, 0.2245],
         ...,
         [0.2637, 0.2716, 0.2755,  ..., 0.2755, 0.2755, 0.2716],
         [0.2637, 0.2716, 0.2755,  ..., 0.2755, 0.2755, 0.2716],
         [0.2637, 0.2755, 0.2833,  ..., 0.2716, 0.2755, 0.2716]],

        [[0.2206, 0.2206, 0.2206,  ..., 0.2324, 0.2324, 0.2363],
         [0.2206, 0.2206, 0.2206,  ..., 0.2324, 0.2324, 0.2363],
         [0.2206, 0.2206, 0.2206,  ..., 0.2324, 0.2324, 0.2363],
         ...,
         [0.2755, 0.2833, 0.2912,  ..., 0.2912, 0.2912, 0.2912],
         [0.2716, 0.2794, 0.2912,  ..., 0.2873, 0.2912, 0.2912],
         [0.2716, 0.2833, 0.2912,  ..., 0.2833, 0.2873, 0.2912]],

        [[0.2284, 0.2284, 0.2324,  ..., 0.2559, 0.2559, 0.2598],
         [0.2284, 0.2324, 0.2324,  ..., 0.2559, 0.2559, 0.2598],
         [0.2284, 0.2324, 0.2324,  ..., 0.2520, 