In [15]:
import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np
import pandas as pd

# DataLoader

批量处理（batch）：如每次处理4个样本

数据打乱（shuffle）：训练时打乱数据，避免模型记住顺序；验证/测试时不需要打乱

多进程加载（num_workers）

自动转换为张量

In [17]:
# 继承自 Dataset
class MyDataset(Dataset):
  def __init__(self, ):
    self.x = [i for i in range(10)]
    self.y = [i*2 for i in range(10)]

  def __len__(self):
    return len(self.x)
    
  def __getitem__(self, index):
    return self.x[index], self.y[index]
  
if __name__ == '__main__':
  # 创建数据集对象
  my_dataset = MyDataset()
  #  用 DataLoader 包装数据集
  # jupyter notebook执行不了多进程，只要有num_workers字段就会报错，哪怕值为1
  my_dataloader = DataLoader(my_dataset, batch_size=2)
  # my_dataloader = DataLoader(my_dataset, batch_size=2, num_workers=1)
  for x_i, y_i in my_dataloader:
    print(x_i, y_i) 



tensor([0, 1]) tensor([0, 2])
tensor([2, 3]) tensor([4, 6])
tensor([4, 5]) tensor([ 8, 10])
tensor([6, 7]) tensor([12, 14])
tensor([8, 9]) tensor([16, 18])


In [26]:
class MyDataset(Dataset):
  def __init__(self):
    filename = '/Users/yafei/practice/python-practice/基础学习/pytorch/tensor/模仿数据读取.xlsx'  
    data = pd.read_excel(filename)
    self.x1 = data['x1']
    self.x2 = data['x2']
    self.x3 = data['x3']
    self.x4 = data['x4']
    self.y = data['y']
    print(data)
    # print(data['x1'])
    
  def __len__(self):
    return len(self.x1)
  
  def __getitem__(self, item):
    return self.x1[item], self.x2[item], self.x3[item], self.x4[item], self.y[item]
  
if __name__ == '__main__':
  my_dataset = MyDataset()
  my_dataloader = DataLoader(my_dataset, shuffle=True)
  
  for x1, x2, x3, x4, y in my_dataloader:
    print(x1, x2, x3, x4, y)
  







    x1    x2   x3  x4  y
0    1  0.01   95   2  1
1    2  0.02   96   4  0
2    3  0.03   97   6  1
3    4  0.04   98   8  0
4    5  0.05   99  10  1
5    6  0.06  100  12  0
6    7  0.07  101  14  1
7    8  0.08  102  16  0
8    9  0.09  103  18  1
9   10  0.10  104  20  0
10  11  0.11  105  22  1
11  12  0.12  106  24  0
12  13  0.13  107  26  1
13  14  0.14  108  28  0
14  15  0.15  109  30  1
15  16  0.16  110  32  0
16  17  0.17  111  34  1
17  18  0.18  112  36  0
18  19  0.19  113  38  1
19  20  0.20  114  40  0
tensor([20]) tensor([0.2000], dtype=torch.float64) tensor([114]) tensor([40]) tensor([0])
tensor([16]) tensor([0.1600], dtype=torch.float64) tensor([110]) tensor([32]) tensor([0])
tensor([13]) tensor([0.1300], dtype=torch.float64) tensor([107]) tensor([26]) tensor([1])
tensor([6]) tensor([0.0600], dtype=torch.float64) tensor([100]) tensor([12]) tensor([0])
tensor([18]) tensor([0.1800], dtype=torch.float64) tensor([112]) tensor([36]) tensor([0])
tensor([5]) tensor([0.0500