In [41]:
import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np
import pandas as pd
import os
import cv2 as cv
import torchvision

# DataLoader

批量处理（batch）：如每次处理4个样本

数据打乱（shuffle）：训练时打乱数据，避免模型记住顺序；验证/测试时不需要打乱

多进程加载（num_workers）

自动转换为张量

In [17]:
# 继承自 Dataset
class MyDataset(Dataset):
  def __init__(self, ):
    self.x = [i for i in range(10)]
    self.y = [i*2 for i in range(10)]

  def __len__(self):
    return len(self.x)
    
  def __getitem__(self, index):
    return self.x[index], self.y[index]
  
if __name__ == '__main__':
  # 创建数据集对象
  my_dataset = MyDataset()
  #  用 DataLoader 包装数据集
  # jupyter notebook执行不了多进程，只要有num_workers字段就会报错，哪怕值为1
  my_dataloader = DataLoader(my_dataset, batch_size=2)
  # my_dataloader = DataLoader(my_dataset, batch_size=2, num_workers=1)
  for x_i, y_i in my_dataloader:
    print(x_i, y_i) 



tensor([0, 1]) tensor([0, 2])
tensor([2, 3]) tensor([4, 6])
tensor([4, 5]) tensor([ 8, 10])
tensor([6, 7]) tensor([12, 14])
tensor([8, 9]) tensor([16, 18])


# 导入excel文件到dataset

In [26]:
class MyDataset(Dataset):
  def __init__(self):
    filename = '/Users/yafei/practice/python-practice/基础学习/pytorch/tensor/模仿数据读取.xlsx'  
    data = pd.read_excel(filename)
    self.x1 = data['x1']
    self.x2 = data['x2']
    self.x3 = data['x3']
    self.x4 = data['x4']
    self.y = data['y']
    print(data)
    # print(data['x1'])
    
  def __len__(self):
    return len(self.x1)
  
  def __getitem__(self, item):
    return self.x1[item], self.x2[item], self.x3[item], self.x4[item], self.y[item]
  
if __name__ == '__main__':
  my_dataset = MyDataset()
  my_dataloader = DataLoader(my_dataset, shuffle=True)
  
  for x1, x2, x3, x4, y in my_dataloader:
    print(x1, x2, x3, x4, y)
  







    x1    x2   x3  x4  y
0    1  0.01   95   2  1
1    2  0.02   96   4  0
2    3  0.03   97   6  1
3    4  0.04   98   8  0
4    5  0.05   99  10  1
5    6  0.06  100  12  0
6    7  0.07  101  14  1
7    8  0.08  102  16  0
8    9  0.09  103  18  1
9   10  0.10  104  20  0
10  11  0.11  105  22  1
11  12  0.12  106  24  0
12  13  0.13  107  26  1
13  14  0.14  108  28  0
14  15  0.15  109  30  1
15  16  0.16  110  32  0
16  17  0.17  111  34  1
17  18  0.18  112  36  0
18  19  0.19  113  38  1
19  20  0.20  114  40  0
tensor([20]) tensor([0.2000], dtype=torch.float64) tensor([114]) tensor([40]) tensor([0])
tensor([16]) tensor([0.1600], dtype=torch.float64) tensor([110]) tensor([32]) tensor([0])
tensor([13]) tensor([0.1300], dtype=torch.float64) tensor([107]) tensor([26]) tensor([1])
tensor([6]) tensor([0.0600], dtype=torch.float64) tensor([100]) tensor([12]) tensor([0])
tensor([18]) tensor([0.1800], dtype=torch.float64) tensor([112]) tensor([36]) tensor([0])
tensor([5]) tensor([0.0500

# 导入图像数据集到Dataset

In [ ]:
image_root = '/Users/yafei/practice/python-practice/基础学习/pytorch/tensor/animals'

for root, dirs, files in os.walk(image_root):
  print(f"当前目录: {root}")
  print(f"子目录: {dirs}")
  print(f"文件: {files}")
  print("-" * 50)
  # 只遍历前3个目录作为示例
  if len(files) > 0:
    for file_i in files:
      file_i_full_path = os.path.join(root, file_i)
      print(file_i_full_path)
      img_i = cv.imread(file_i_full_path)
      cv.imshow('img_i', img_i)
      cv.waitKey(500)
      # cv.destroyAllWindows()





当前目录: /Users/yafei/practice/python-practice/基础学习/pytorch/tensor/animals
子目录: ['hippopotamus', 'sparrow', 'gorilla', 'cat', 'rhinoceros', 'wombat', 'seahorse', 'butterfly', 'donkey', 'raccoon', 'dragonfly', 'crab', 'pig', 'orangutan', 'turtle', 'antelope', 'dog', 'bee', 'coyote', 'fox', 'pigeon', 'dolphin', 'fly', 'turkey', 'boar', 'goldfish', 'hare', 'bear', 'penguin', 'squid', 'zebra', 'leopard', 'sheep', 'hamster', 'panda', 'mosquito', 'lobster', 'duck', 'ox', 'owl', 'tiger', 'whale', 'crow', 'rat', 'moth', 'eagle', 'reindeer', 'grasshopper', 'otter', 'starfish', 'hyena', 'goat', 'sandpiper', 'seal', 'jellyfish', 'hummingbird', 'mouse', 'hornbill', 'porcupine', 'wolf', 'lizard', 'woodpecker', 'beetle', 'chimpanzee', 'parrot', 'kangaroo', 'pelecaniformes', 'oyster', 'caterpillar', 'okapi', 'ladybugs', 'bat', 'cockroach', 'koala', 'swan', 'octopus', 'hedgehog', 'horse', 'flamingo', 'squirrel', 'bison', 'cow', 'deer', 'lion', 'goose', 'shark', 'snake', 'badger', 'elephant', 'possum']
文件

In [40]:
class MyImageDataset(Dataset):
  def __init__(self):
    self.image_root = '/Users/yafei/practice/python-practice/基础学习/pytorch/tensor/animals'
    self.file_path_list = []
    self.labels = []
    dir_name = []
    for root, dirs, files in os.walk(self.image_root):
      if dirs:
        dir_name = dirs
      for file_i in files:
        file_i_full_path = os.path.join(root, file_i)
        self.file_path_list.append(file_i_full_path)
        
        label = root.split(os.sep)[-1]  # os.sep表示'/'
        label_id = dir_name.index(label)
        self.labels.append(label_id)
        
  def __len__(self):
    return len(self.file_path_list)
  
  def __getitem__(self, item):
    img = cv.imread(self.file_path_list[item])
    img = cv.resize(img, (256, 256))
    # HWC 默认是
    #tensor里的格式是 CHW
    img = np.transpose(img, (2, 0, 1))
    img_tensor = torch.from_numpy(img)
    label = self.labels[item]
    return img_tensor, label
  
if __name__ == '__main__':
  my_image_dataset = MyImageDataset()
  my_dataloader = DataLoader(my_image_dataset, shuffle=True)
  for tensor_data, label_id in my_dataloader:
    print(tensor_data.shape, label_id)
  

torch.Size([1, 3, 256, 256]) tensor([67])
torch.Size([1, 3, 256, 256]) tensor([70])
torch.Size([1, 3, 256, 256]) tensor([11])
torch.Size([1, 3, 256, 256]) tensor([22])
torch.Size([1, 3, 256, 256]) tensor([48])
torch.Size([1, 3, 256, 256]) tensor([16])
torch.Size([1, 3, 256, 256]) tensor([18])
torch.Size([1, 3, 256, 256]) tensor([30])
torch.Size([1, 3, 256, 256]) tensor([83])
torch.Size([1, 3, 256, 256]) tensor([74])
torch.Size([1, 3, 256, 256]) tensor([9])
torch.Size([1, 3, 256, 256]) tensor([35])
torch.Size([1, 3, 256, 256]) tensor([69])
torch.Size([1, 3, 256, 256]) tensor([81])
torch.Size([1, 3, 256, 256]) tensor([15])
torch.Size([1, 3, 256, 256]) tensor([1])
torch.Size([1, 3, 256, 256]) tensor([31])
torch.Size([1, 3, 256, 256]) tensor([9])
torch.Size([1, 3, 256, 256]) tensor([57])
torch.Size([1, 3, 256, 256]) tensor([88])
torch.Size([1, 3, 256, 256]) tensor([53])
torch.Size([1, 3, 256, 256]) tensor([5])
torch.Size([1, 3, 256, 256]) tensor([62])
torch.Size([1, 3, 256, 256]) tensor([3

# 加载torch官方数据集
https://docs.pytorch.org/vision/stable/datasets.html

In [ ]:
transform = torchvision.transforms.ToTensor()

trainset = torchvision.datasets.MNIST(root='./data', train=True,  download=True, transform=transform)
trainloader = DataLoader(trainset, shuffle=True)
# trainloader = DataLoader(trainset, batch_size=4, shuffle=True)

testset = torchvision.datasets.MNIST(root='./data', train=False,  download=True, transform=transform)
testloader = DataLoader(testset, shuffle=False)
# testloader = DataLoader(testset, batch_size=4, shuffle=False)


for x,y in trainloader:
    print(x.shape, y)

for x,y in testloader:
    print(x.shape, y)